### ISSUE TITLE
Georeferencing Error: Records found outside named county > .5 mile

### ISSUE THREAD

**Issue by dbloom** [rom-vertnet/mammalogyspecimens#25]
Hello ROM,

The Kentucky Department of Fish & Wildlife Resources, Fish and Wildlife Information System (KFWIS) have identified 1 record in the VertNet data portal that should plot within the bounds of the named county in the state of Kentucky, but actually plots outside the named county by half a mile or more.

If you'd like to discuss this issue with the folks at KFWIS, contact me and I will connect you with them.

institutioncode	collectioncode	catalognumber	county	decimallatitude	decimallongitude	geodeticdatum	coordinateuncertaintyinmeters
Royal Ontario Museum: ROM	Mammals	78715	Breathitt	38.4919	-84.3487	NAD27	0

 (There may not be data contained within each Darwin Core field for each of these records.)

**Comment by bradmROM** [comment]
Hey:
I will  have a look today after lunch and get back to you.  
Brad


Sent from Brad's Samsung Galaxy Mobile Note 3

-------- Original message --------

**Comment by bradmROM** [comment]
Well. I just plotted these coordinates. 

It most certainly does not fall within the Breathitt County as it states in the record. It is Harrison County, Kentucky. The GeoreferenceVerificationStatus states that it is "unverified". This is a potential for errors in the original data regarding coordinates and Higher Geography. So, the next time our records are polled it will be updated.
